"""Initial

Revision ID: 1108eeaf4867
Revises: 
Create Date: 2025-01-28 23:08:42.677675

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "1108eeaf4867"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column(
            "message_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("sender_name", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_msg_num", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
        sa.UniqueConstraint(
            "sender_name", "user_msg_num", name="uq_sender_msgnum"
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("last_msg_num", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("messages")
    # ### end Alembic commands ###
